#!/bin/bash

wspath="./workspaces"

if [ -z "$1" ] ; then
	echo "Args: workspacename [json-file]" ; echo ; exit 1
fi

wsname="$1"
wsfname="$2"

if [ -z "$wsfname" ] ; then
	# remove everything left of whitepsace
	wsfname="${1/#* /}.json"
fi

launcher="$wspath/${wsfname/json/sh}"

if [ ! -x "$launcher" ] ; then
	echo "$launcher is not executable."
	exit 1;
fi

i3-msg "workspace $wsname; append_layout $wspath/$wsfname" && $launcher
